import type { Metadata } from "next";
import { fonts } from "@/lib/fonts";
import ThemeProvider from "@/components/ThemeProvider";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { AuthProvider } from "@/components/AuthProvider";
import { getSession } from "@/utils/quries/auth";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }: LayoutProps<"/">) {
  const user = await getSession();

  return (
    <html lang="en" className={fonts} suppressHydrationWarning>
      <body className="h-full min-h-dvh w-full bg-white font-sans text-base font-normal antialiased">
        <ThemeProvider
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <AuthProvider user={user}>{children}</AuthProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
